---
title: "Covid CMAJ Analysis"
author:
- name: Luke Anderson-Trocmé,
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---
# Load libraries and set paths
```{r setup}
pacman::p_load(drat) #to download latest covdata
pacman::p_load(ggplot2) # plotting functions
pacman::p_load(cowplot) # combine plots
pacman::p_load(ggrepel) # repel label text
pacman::p_load(dplyr) # data wrangling
pacman::p_load(broom)
pacman::p_load(jsonlite)
pacman::p_load(data.table)
pacman::p_load(tidyverse)
pacman::p_load(tsibble) # for difference function
pacman::p_load(lubridate)
pacman::p_load(colorspace)
pacman::p_load(ggthemes)
pacman::p_load(locfit)
pacman::p_load(zoo)

#Set Path
covidPath <- '~/Documents/covid19/data/world/'
covidFigPath <- '~/Documents/covid19/figures/'
```
##Provincial Data
```{r}
##################################################
# Google mobility trends
# https://www.google.com/covid19/mobility/
##################################################
mobility_data_can <- 
  fread(paste0(covidPath, "Global_Mobility_Report.csv"), sep = ",", header = T) %>%
  filter(country_region == "Canada")  %>% 
  rename(prname = sub_region_1) %>%
  mutate(date = as.Date(date))

##################################################
##################################################
can_lockdown <- 
  read.csv(paste0(covidPath,"../canada/can_lockdown.csv"), 
           colClasses = c("character","character","Date")) %>% rename(prname = region_name)


##################################################
#"https://www150.statcan.gc.ca/n1/tbl/csv/17100009-eng.zip"
##################################################
pop_sizes <- 
  read.csv(paste0(covidPath, "17100009.csv")) %>%
  group_by(GEO) %>%
  top_n( . , 1, REF_DATE) %>%
  rename(prname = GEO,
         pop_size = VALUE) %>%
  dplyr::select(prname, pop_size)

can_data_url <- "https://health-infobase.canada.ca/src/data/covidLive/covid19.csv"
download.file(paste0(can_data_url),destfile = paste0(covidPath, "can_covid19.csv"), quiet = T)


case_limit <- 10

prov <-
  read.csv(paste0(covidPath, "can_covid19.csv")) %>% 
  mutate(date = as.Date(as.character(date),format="%d-%m-%Y")) %>%
  inner_join( . ,
              can_lockdown,
              by = "prname") %>%
  inner_join( . ,
              pop_sizes,
              by = "prname") %>%
  #inner_join(. ,
  #           mobility_data_can,
  #           by = c("prname","date")) %>%
  filter(numconf > case_limit) %>%
  arrange(date) %>%
  group_by(prname) %>%
  mutate(capita_cases = numconf / pop_size * 1e6,
         cases_logratio = tsibble::difference(log(numconf)),
         capita_cases_logratio = tsibble::difference(log(capita_cases)),
         doubling_time = log(2) / cases_logratio,
         positive_rate = numconf / numtested * 1000,
         capita_positive_rate = (numconf / numtested * 1000) / pop_size * 1e6,
         from_shutdown = as.numeric(difftime(date, lockdown_date, units = "days")),
         end_label = ifelse(date == max(date), prabb, NA),
         days_elapsed = as.numeric(date - min(date)),
         max_case = max(numconf, na.rm = T))

prov <-
  prov %>% 
  filter(doubling_time < Inf,
         prname != "Canada") %>%
  group_by(prname) %>%
  do(augment(loess(doubling_time ~ days_elapsed, .))) %>% 
  inner_join(. , prov,
             by = c("prname", "days_elapsed", "doubling_time")) %>%
  mutate(max_days = max(days_elapsed, na.rm = T),
         end_label = ifelse(days_elapsed == max_days, 
                            as.character(prname), NA))

prov$prname <- reorder(prov$prname, prov$max_case)

prov


death_count_can <-
  prov %>%
  group_by(prname) %>%
  mutate(bad_day = ifelse(.fitted < 14, 1, 0)) %>%
  dplyr::summarise(tests = max(numtested, na.rm = T),
                   death = max(numdeaths),
                   sum_bad = sum(bad_day))


```

#Fancy plotting tid bits 
```{r}

## rescale doubling time to reverse
#https://stackoverflow.com/questions/11053899/how-to-get-a-reversed-log10-scale-in-ggplot2
library("scales")
reverselog_trans <- function(base = exp(1)) {
  trans <- function(x) -log(x, base)
  inv <- function(x) base^(-x)
  trans_new(paste0("reverselog-", format(base)), trans, inv, 
            log_breaks(base = base), 
            domain = c(1e-100, Inf))
}


label_can <- 
  prov %>%
  filter(is.na(numtested) == F,
         is.na(numtotal) == F) %>%
  group_by(prname) %>%
  top_n( ., 1, wt = days_elapsed) %>%
  mutate(end_label = prname)
```

#positive rate
```{r}
pr_can <-
ggplot(prov %>%
         filter(!positive_rate == F),
       aes(x = days_elapsed, 
           y = positive_rate,  
           group = prname,
           color = prname,
           label = end_label)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "locfit",size = 1.5, se = F) + 
  geom_label_repel(data = label_can,
                  aes(x = days_elapsed, 
                      y = positive_rate,
                      group = prname,
                      label = end_label),
                  color = "black",
                  alpha = 0.3,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  geom_label_repel(data = label_can,
                  aes(x = days_elapsed, 
                      y = positive_rate,
                      group = prname,
                      label = end_label),
                  color = "black",
                  fill = NA,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  labs(y = "Number of Cases per 1000 Tests",
       x = paste("Days Since",case_limit,"Confirmed Cases"))+
  scale_color_discrete_qualitative() +
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))

cu_can <-
  ggplot(prov,
         aes(x = days_elapsed, 
             y = numtotal,  
             group = prname,
             color = prname,
             label = end_label)) + 
  geom_line(size = 1.5) + 
  geom_label_repel(data = label_can,
                  aes(x = days_elapsed, 
                      y = numtotal,
                      group = prname,
                      label = end_label),
                  color = "black",
                  alpha = 0.3,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  geom_label_repel(data = label_can,
                  aes(x = days_elapsed, 
                      y = numtotal,
                      group = prname,
                      label = end_label),
                  color = "black",
                  fill = NA,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  labs(y = "Number of Confirmed Cases",
       x = paste("Days Since",case_limit,"Confirmed Cases"))+
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(0, 15, 3) * 100,
                     trans = "log2",
                     limits = c(10, 100000)) +
  scale_color_discrete_qualitative()+
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))

plot_grid(cu_can, pr_can, ncol =1, align = "v", axis = "b", labels = "AUTO")

ggsave(paste0(covidFigPath,"fig1_analysis.jpg"), height = 10, width = 8)
```

#positive rate per capita
```{r}
pr_can_cap <-
ggplot(prov %>%
         filter(!capita_positive_rate == F,
                prname %in% c("Ontario","Quebec","Alberta", "British Columbia")),
       aes(x = days_elapsed, 
           y = capita_positive_rate/10,  
           group = prname,
           color = prname,
           label = end_label)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "locfit",size = 1.5, se = F) + 
  geom_label_repel(data = label_can %>%
         filter(prname %in% c("Ontario","Quebec","Alberta", "British Columbia")),
                  aes(x = days_elapsed, 
                      y = capita_positive_rate /10,
                      group = prname,
                      label = end_label),
                  fontface = "bold",
                  color = "black") +
  labs(y = "positivity rate per 1 million people (%)",
       x = paste("Days Since",10,"Confirmed Cases"))+
  scale_color_discrete_qualitative() +
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))

cu_can_cap <-
  ggplot(prov %>%
         filter(prname %in% c("Ontario","Quebec","Alberta", "British Columbia")),
         aes(x = days_elapsed, 
             y = capita_cases,  
             group = prname,
             color = prname,
             label = end_label)) + 
  geom_line(size = 1.5) + 
  geom_label_repel(data = label_can %>%
         filter(prname %in% c("Ontario","Quebec","Alberta", "British Columbia")),
                  aes(x = days_elapsed, 
                      y = capita_cases,
                      group = prname,
                      label = end_label),
                  fontface = "bold",
                  color = "black") +
  labs(y = "cases per 1 million people",
       x = paste("Days Since",10,"Confirmed Cases"))+
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-2, 15, 1) * 100,
                     trans = "log2",
                     limits = c(10, 30000)) +
  scale_color_discrete_qualitative()+
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))

plot_grid(cu_can_cap, pr_can_cap, ncol =1, align = "v", axis = "b", labels = "AUTO")

ggsave(paste0(covidFigPath,"fig1_analysis_percap_sub.jpg"), height = 10, width = 8)
```


# Load data
```{r, warning = F, message = F}
##################################################
# Coronavirus testing data
# https://ourworldindata.org/coronavirus
##################################################
data_url <- "https://covid.ourworldindata.org/data/owid-covid-data.csv"
# Download data
download.file(data_url, destfile = paste0(covidPath, "owid-covid-data.csv"), quiet = T)

testing <- read.csv(paste0(covidPath,"owid-covid-data.csv")) %>%
  mutate(date = as.Date(date),
         country_region = location)

##################################################
##Government Policy Stringency index
#https://ocgptweb.azurewebsites.net/CSVDownload
##################################################
data_url <- "https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv"
# Download data
download.file(data_url, destfile = paste0(covidPath, "OxCGRT_latest.csv"), quiet = T)

# Load and format
OxCGRT <- read.csv(paste0(covidPath, "OxCGRT_latest.csv"))%>%
  mutate(date  = as.Date(as.character(Date),format="%Y%m%d")) %>%
  rename(country_region = CountryName)

##################################################
# Government policy implementation date (Wikipedia)
##################################################
lockdown <- read.csv(paste0(covidPath,"lockdown.csv"), 
                     colClasses = c("character","Date","Date"))

##################################################
# Google mobility trends
# https://www.google.com/covid19/mobility/
##################################################
mobility_data <- 
  fread(paste0(covidPath, "Global_Mobility_Report.csv"), sep = ",", header = T) %>%
  filter(sub_region_1 == "",
         sub_region_2 == "")  %>% 
  mutate(date = as.Date(date))


## Countries to highlight
case_countries <- c("United States","Italy","Canada", "South Korea", "New Zealand")

hand_pick <-
  c("United States","Italy","Canada", "South Korea", "Singapore", "New Zealand", "Iceland","Australia","Austria", "Estonia","Slovenia","Greece", "Malaysia", "Switzerland", "Norway", "Denmark","Ireland","Portugal","Czech Republic", "France", "Germany", "Spain", "Netherlands", "Belgium", "Bahrain", "Finland", "Sweden", "United Kingdom", "Japan")
```

#Combine and process data
```{r}

covid <-
  testing %>%
  filter(total_cases >= case_limit) %>%
  arrange(date) %>%
  group_by(country_region)%>% 
  mutate(cases_logratio = tsibble::difference(log(total_cases)),
         doubling_time = log(2) / cases_logratio,
         days_elapsed = as.numeric(date - min(date)),
         max_case = max(total_cases, na.rm = T))

covid$country_region <- fct_reorder(covid$country_region, covid$max_case)

#get loess regression line
covid <-
  covid %>% 
  filter(doubling_time < Inf,
         country_region %in% hand_pick) %>%
  group_by(country_region) %>%
  do(augment(loess(doubling_time ~ days_elapsed, .))) %>% 
  inner_join(. , covid,
             by = c("country_region", "days_elapsed", "doubling_time")) %>%
  mutate(max_days = max(days_elapsed, na.rm = T),
         end_label = ifelse(days_elapsed == max_days, 
                            as.character(country_region), NA))

dc <-
  covid %>%
  group_by(country_region) %>%
  mutate(bad_day = ifelse(.fitted < 14, 1, 0)) %>%
  dplyr::summarise(tests = max(total_tests_per_thousand, na.rm = T),
                   death = max(total_deaths),
                   sum_bad = sum(bad_day))

covid
dc

subset <- covid %>%
           filter(country_region %in% case_countries)
```

```{r}
label2 <- 
  covid %>%
  filter(is.na(total_tests) == F,
         is.na(total_cases) == F) %>%
  group_by(country_region) %>%
  top_n( ., 1, wt = days_elapsed) %>%
  mutate(end_label = country_region)

cu_w <-
  ggplot(subset %>%
           filter(country_region %in% case_countries),
         aes(x = days_elapsed, 
             y = total_cases,  
             group = country_region,
             color = country_region,
             label = end_label)) + 
  geom_line(size = 1.5) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(1, 15, 3) * 100,
                     trans = "log2",
                     limits = c(case_limit, 2000000)) +
  geom_label_repel(data = label2 %>%
                    filter(country_region %in% case_countries),
                  aes(x = days_elapsed, 
                      y = total_cases,
                      group = country_region,
                      label = end_label),
                  alpha = 0.3,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  geom_label_repel(data = label2 %>%
                    filter(country_region %in% case_countries),
                  aes(x = days_elapsed, 
                      y = total_cases,
                      group = country_region,
                      label = end_label),
                  color = "black",
                  fill = NA,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  labs(y = "Cumulative Number of Confirmed Cases",
       x = paste("Days Since",case_limit,"Confirmed Cases"))+
  scale_color_discrete_qualitative()+
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text.y = element_text(size = 15),
        axis.text.x = element_text(size = 15),
        axis.title = element_text(size = 15))

pr_w <-
  ggplot(subset %>%
           filter(country_region %in% case_countries),
         aes(x = days_elapsed, 
             y = total_cases / total_tests * 1000,  
             group = country_region,
             color = country_region,
             label = end_label)) + 
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "locfit",size = 1.5, se = F) + 
  geom_label_repel(data = label2 %>%
                    filter(country_region %in% case_countries),
                  aes(x = days_elapsed, 
                      y = total_cases / total_tests * 1000,
                      group = country_region,
                      label = end_label),
                  alpha = 0.3,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  geom_label_repel(data = label2 %>%
                    filter(country_region %in% case_countries),
                  aes(x = days_elapsed, 
                      y = total_cases / total_tests * 1000,
                      group = country_region,
                      label = end_label),
                  color = "black",
                  fill = NA,
                  size = 3.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  labs(y = "Number of Cases per 1000 Tests",
       x = paste("Days Since",case_limit,"Confirmed Cases"))+
  scale_color_discrete_qualitative()+
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))


plot_grid(cu_w, pr_w, ncol =1, align = "v", axis = "b", labels = "AUTO")
ggsave(paste0(covidFigPath,"fig2_analysis.jpg"), height = 10, width = 8)
```


