---
title: "Covid in Ontario"
author:
- name: Luke Anderson-Trocmé,
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---
# Load Libraries and set paths
```{r setup}
library(ggplot2)   # plotting functions
library(ggrepel)   # repel label text
library(cowplot)   # combine plots
library(dplyr)     # data wrangling
library(tidyverse) # data wrangling

#Set Path
covidPath <- '~/Documents/covid19/data/ontario/'
covidFigPath <- '~/Documents/covid19/figures/'

today <- format(Sys.Date(), "%B-%d-%Y")
```
# Load Data
```{r, warning = F, message = F}
# Corona virus data is downloaded from : 
data_url <- "https://data.ontario.ca/dataset/f4112442-bdc8-45d2-be3c-12efae72fb27/resource/455fd63b-603d-4608-8216-7d8647f43350/download/conposcovidloc.csv"

# Download data
download.file(data_url, destfile = paste0(covidPath, "conposcovidloc.csv"), quiet = T)


#Location Maps
#get Canadian borders
canada <- raster::getData(name = "GADM",
                          country = "CAN",
                          level = 1)
#get Quebec borders
ON <- canada[canada$NAME_1 %in% "Ontario",]

# Load data
covid_on <- 
  read.csv(paste0(covidPath, "conposcovidloc.csv")) %>%
  mutate(Accurate_Episode_Date = as.Date(Accurate_Episode_Date))

#header of the data
covid_on

#group by city
loc_covid_on <-
  covid_on %>%
  group_by(Reporting_PHU_Latitude, Reporting_PHU_Longitude,Reporting_PHU_City) %>%
  dplyr::summarise(count = n()) %>%
  arrange(-count, Reporting_PHU_City) %>%
  filter(count >= 100)
```
#Make Plots
## Map of Cases in Ontario
```{r, message = F}
#new map limits
Lat1 <- min(loc_covid_on$Reporting_PHU_Latitude, na.rm = T) - 0.8
Lat2 <- max(loc_covid_on$Reporting_PHU_Latitude, na.rm = T) + 0.2
Lon1 <- min(loc_covid_on$Reporting_PHU_Longitude, na.rm = T) - 0.2
Lon2 <- max(loc_covid_on$Reporting_PHU_Longitude, na.rm = T) + 0.2
#crop
new.ext.on <- raster::extent(c(Lon1,Lon2,Lat1,Lat2))
ON <- raster::crop(ON, new.ext.on)

set.seed(101)

ontario_map <-
  ggplot(ON,aes(x=long,y=lat)) +
  geom_path(aes(group = group),
            color = 'grey70') +
  coord_map() +
  geom_point(data = loc_covid_on,
             aes(x=Reporting_PHU_Longitude,
                 y=Reporting_PHU_Latitude ,
                 size = count),
             color = "red",
             alpha = 0.3) +
  geom_point(data = loc_covid_on %>%
               arrange(count),
             aes(x=Reporting_PHU_Longitude,
                 y=Reporting_PHU_Latitude,
                 size = count),
             color = "red",
             shape = 1) +
  geom_text_repel(data = loc_covid_on,
                  aes(x=Reporting_PHU_Longitude,
                      y=Reporting_PHU_Latitude,
                      label = Reporting_PHU_City),
                  segment.alpha = 0.3,
                  fontface= "bold") +
  scale_size_area(breaks = c(250,500,1000,2000),
                  max_size = 15,
                  name = "Count") +
  scale_color_distiller(palette = "RdYlGn",
                        direction = -1,
                        trans = "log10",
                        guide = FALSE) +
  labs(title = paste0("Cities with more than 100 cases")) +
  theme_classic() + 
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 20))

ontario_map

ggsave(paste0(covidFigPath,"Ontario_Covid_",today,"_map.jpg"), height = 10, width = 15)
```
## Cases by city
```{r, warning=F}
covid_on_total <-
  covid_on %>%
  group_by(Accurate_Episode_Date) %>%
  dplyr::summarise(ontario_total_day = n()) %>%
  mutate(total_cumulative = cumsum(ontario_total_day),
         Reporting_PHU_City = "Total") 

lab <- 
  tail(covid_on_total, 1) %>% 
  dplyr::select(Accurate_Episode_Date, Reporting_PHU_City, total_cumulative)

covid_on_city <-
  covid_on %>%
  group_by(Reporting_PHU_City) %>%
  dplyr::summarise(total = n()) %>%
  left_join( . , covid_on, by = "Reporting_PHU_City")

covid_on_city <-
  covid_on_city %>%
  group_by(Accurate_Episode_Date, Reporting_PHU_City) %>%
  dplyr::summarise(city_total_day = n()) %>%
  group_by(Reporting_PHU_City) %>%
  mutate(total_cumulative = cumsum(city_total_day)) %>%
  left_join( . , covid_on_city, by = c("Accurate_Episode_Date","Reporting_PHU_City")) %>%
  arrange(Reporting_PHU_City, Accurate_Episode_Date)

days_since <-
  covid_on_city %>%
  dplyr::select(Reporting_PHU_City, Accurate_Episode_Date, total_cumulative) %>% 
  #bind_rows(.,covid_on_total) %>%
  filter(total_cumulative >= 10) %>%
  unique() %>%
  arrange(Reporting_PHU_City, Accurate_Episode_Date) %>%
  group_by(Reporting_PHU_City) %>%
  mutate(days = row_number())

covid_on_labels <-
  days_since %>%
  dplyr::select(Accurate_Episode_Date, days, Reporting_PHU_City, total_cumulative) %>%
  group_by(Reporting_PHU_City) %>%
  top_n(x = . , n = 1, wt = Accurate_Episode_Date) %>%
  ungroup() %>%
  #top_n(x = ., n = 11, wt = total_cumulative) %>%
  mutate(city_name = paste(Reporting_PHU_City, total_cumulative, sep = " : "))


rate <-
  days_since %>%
  dplyr::select(Accurate_Episode_Date, Reporting_PHU_City, total_cumulative) %>%
  arrange(Accurate_Episode_Date) %>%
  group_by(Reporting_PHU_City) %>%
  mutate(time_diff = as.numeric(Accurate_Episode_Date - lag(Accurate_Episode_Date)),  # just in case there are gaps in data
         case_diff = total_cumulative - lag(total_cumulative), # count diff in cases between dates
         rate_percent = ( case_diff / time_diff ) / lag(total_cumulative) * 100) %>%# growth rate
  filter(Reporting_PHU_City != "Total") %>%
  group_by(Reporting_PHU_City) %>%
  filter(rate_percent < Inf) %>% # remove infinity from mean rate
  dplyr::summarise(growth_rate = mean(rate_percent, na.rm = TRUE),
                   double_time = log(2) / growth_rate ) %>%
  left_join( . ,
             days_since, 
             by = "Reporting_PHU_City")
```

```{r, fig.height=10}
city_path <-
  ggplot()+
  geom_path(data = rate,
            aes(x = days,
                y = total_cumulative,
                color = growth_rate,
                group = Reporting_PHU_City)) +
    geom_point(data = rate,
            aes(x = days,
                y = total_cumulative,
                color = growth_rate)) +
  geom_label_repel(data = covid_on_labels %>%
                    filter(total_cumulative >= 50),
                  aes(x = days, 
                      y = total_cumulative,
                      label = city_name),
                  color = "black",
                  alpha = 0.3,
                  size = 2.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
    geom_label_repel(data = covid_on_labels %>%
                    filter(total_cumulative >= 50),
                  aes(x = days, 
                      y = total_cumulative,
                      label = city_name),
                  color = "black",
                  fill = NA,
                  size = 2.5,
                  box.padding = 0.8,
                  hjust = 1,
                  force = 0.1,
                  segment.alpha = 0.3,
                  fontface = "bold",
                  seed = 1234) +
  annotation_logticks(sides = "l") +
  scale_y_continuous(trans = "log2")+
  scale_color_distiller(palette = "Reds",
                        direction = 1,
                        name = "Growth Rate (%)") +
  theme_bw() +
  labs(x = "Days since 10th case",
       y = "Total number of cases") +
  ggtitle("Cases over time") +
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        panel.grid.minor = element_blank(),
        axis.title = element_text(size = 15))

city_path

ggsave(paste0(covidFigPath,"Ontario_Covid_",today,"_days.jpg"), height = 10, width = 20)
```

## Age distribution of Covid-19 cases
```{r}
age_group <-
  ggplot(covid_on%>%
           filter(Age_Group != "Unknown",
                  Accurate_Episode_Date >= as.Date("2020-03-01")),
         aes(x = Accurate_Episode_Date,
             fill = fct_rev(Age_Group))) +
  geom_histogram(binwidth = 1) +
  scale_fill_brewer(palette = "Reds",
                    type = "seq",
                    direction = -1,
                    name = "Age Group") +
  labs(x = "Date",
       y = "Total number of cases",
       title = paste0("Age distribution of cases")) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        panel.grid.minor = element_blank(),
        axis.title = element_text(size = 15))

age_group

ggsave(paste0(covidFigPath,"Ontario_Covid_",today,"_age_bin.jpg"), height = 7, width = 10)
```

##Case information of COVID-19
```{r}
case_info<-
  ggplot(covid_on %>%
           filter(Accurate_Episode_Date >= as.Date("2020-03-01")),
         aes(x = Accurate_Episode_Date,
             fill = Case_AcquisitionInfo)) +
  geom_histogram() +
  scale_fill_brewer(palette = "Reds",
                    name = "Case Info",
                    direction = -1) +
  labs(x = "Date",
       y = "Total number of cases",
       title = paste0("Case information")) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        panel.grid.minor = element_blank(),
        axis.title = element_text(size = 15)) #+
  #xlim(c(start_on,end_on))

case_info

ggsave(paste0(covidFigPath,"Ontario_Covid_",today,"_case_info.jpg"), height = 7, width = 10)
```
##Age distribution of COVID-19 outcomes 
```{r}
outcomes <-
  ggplot(covid_on %>%
           filter(Age_Group != "Unknown",
                  Accurate_Episode_Date >= as.Date("2020-03-01")),
         aes(x = Age_Group,
             fill = Outcome1,
             group = Outcome1)) +
  geom_histogram(stat = "count",
                 size = 2,
                 position = "dodge") +
  scale_fill_brewer(palette = "Reds", direction = -1, name = "Outcome") +
  labs(x = "Age Group",
       y = "Total number of cases",
       title = paste0("Age distribution of outcomes")) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        panel.grid.minor.x = element_blank(),
        axis.title = element_text(size = 15))

outcomes

ggsave(paste0(covidFigPath,"Ontario_Covid_",today,"_outcome.jpg"), height = 7, width = 10)
```

```{r, fig.height=10}

title <- ggdraw() + 
  draw_label(
    paste0("Covid Cases in Ontario (",today,")"),
    fontface = 'bold',
    hjust = 0.5,
    size = 25)

combined_plots <-
  plot_grid(title,
    plot_grid(ontario_map, 
              city_path,
              nrow = 1,
              align = "v",
              axis = "l"),
    plot_grid(age_group,
              case_info,
              outcomes,
              nrow = 1,
              align = "h",
              axis = "b"),
    nrow = 3,
    rel_heights = c(0.2, 1, 0.6))

combined_plots

ggsave(paste0(covidFigPath,"Ontario_Covid_",today,"_summary.jpg"), height = 10, width = 20)
```