---
title: "Covid Log Ratio"
author:
- name: Luke Anderson-Trocmé,
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---
# Load Libraries and set paths
```{r setup}
pacman::p_load(ggplot2) # plotting functions
pacman::p_load(cowplot) # combine plots
pacman::p_load(ggrepel) # repel label text
pacman::p_load(dplyr) # data wrangling
pacman::p_load(broom)
pacman::p_load(jsonlite)
pacman::p_load(data.table)
pacman::p_load(tidyverse)
pacman::p_load(tsibble) # for difference function
pacman::p_load(lubridate)
pacman::p_load(colorspace)
pacman::p_load(ggthemes)
pacman::p_load(locfit)
pacman::p_load(zoo)


## rescale doubling time to reverse
#https://stackoverflow.com/questions/11053899/how-to-get-a-reversed-log10-scale-in-ggplot2
library("scales")
reverselog_trans <- function(base = exp(1)) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv, 
              log_breaks(base = base), 
              domain = c(1e-100, Inf))
}




#Set Path
covidPath <- '~/Documents/covid19/data/world/'
covidFigPath <- '~/Documents/covid19/figures/'

today <- format(Sys.Date(), "%Y-%B-%d")
```
# Load Data
```{r, warning = F, message = F}
##################################################
# covdata
# https://github.com/kjhealy/covdata
#remotes::install_github("kjhealy/covdata")
##################################################

library("drat")
drat::addRepo("kjhealy")
install.packages("covdata")
library(tidyverse)
library(covdata)
library(ggrepel)
library(paletteer)
library(prismatic)

covnat

##Stringency index
#https://ocgptweb.azurewebsites.net/CSVDownload
```

##Stringency
```{r}
# Corona virus data is downloaded from : 
data_url <- "https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv"

# Download data
download.file(data_url, destfile = paste0(covidPath, "OxCGRT_latest.csv"), quiet = T)

OxCGRT <- read.csv(paste0(covidPath, "OxCGRT_latest.csv"))%>%
  filter(CountryName %in% case_countries) %>%
  mutate(date  = as.Date(as.character(Date),format="%Y%m%d")) %>%
  rename(country_region = CountryName)


Ox_tip <-
  Ox %>%
  group_by(CountryName) %>%
      distinct(StringencyIndex)%>% 
      arrange(desc(StringencyIndex)) %>% 
      slice(2) %>%
  left_join(.,
            Ox,
            by = c("CountryName","StringencyIndex"))

  ggplot(Ox,
         aes(x = Date, y = StringencyIndex)) +
  geom_line() +
  geom_point(data = Ox_tip,
             aes(x = Date, y = StringencyIndex)) +
  facet_grid(CountryName~.) 
```

```{r}
## Countries to highlight
case_countries <- c("United States","Italy","Canada", "South Korea", "Singapore", "New Zealand", "Japan")
#case_countries <- c("United States","Italy", "Sweden", "Denmark", "South Korea", "Singapore")
#focus_cn <- c("USA","KOR", "ITA", "DNK", "SGP", "SWE", "GBR", "ESP", "FRA", "CAN", "JPN", "NOR","AUT", "AUS")
#case_countries <- c("United States", "Italy", "United Kingdom", "Spain", "France","Canada", "Sweden", "Denmark", "South Korea", "Singapore", "Japan", "Norway","Austria","Australia")
lockdown <- read.csv(paste0(covidPath,"lockdown.csv"), colClasses = c("character","Date","Date"))
testing <- read.csv(paste0(covidPath,"owid-covid-data.csv")) %>%
  mutate(date = as.Date(date),
         country_region = location)

case_study <-
  covnat %>%
  filter(cu_cases > 10) %>%
  mutate(country_region = recode(cname, `Korea, Republic of` = "South Korea"))

mobility_data <- 
  fread(paste0(covidPath, "Global_Mobility_Report.csv"), sep = ",", header = T) %>%
  filter(sub_region_1 == "",
         sub_region_2 == "")  %>% 
  mutate(date = as.Date(date)) %>%
  right_join( . ,
              case_study,
              by = c("country_region","date")) %>% 
  inner_join( . ,
              testing,
              by = c("country_region","date")) %>%
  inner_join( . ,
              lockdown,
              by = "country_region") %>%
  inner_join( . ,
              OxCGRT,
              by = c("country_region","date")) %>%
  filter(country_region %in% case_countries) %>%
  arrange(date) %>%
  group_by(country_region)%>% 
  mutate(cases_logratio = tsibble::difference(log(cu_cases)),
         doubling_time = log(2) / cases_logratio,
         from_shutdown = as.numeric(difftime(date, shutdown_date, units = "days")),
         end_label = ifelse(from_shutdown == max(from_shutdown), country_region, NA),
         days_elapsed = as.numeric(date - min(date))) #%>%
  #filter(from_shutdown > -31)# %>%
  #dplyr::select(country_region, date, from_shutdown, days_elapsed, cases_logratio,doubling_time, cu_cases, cu_deaths, trend,intersects, first_case, end_label)
  
mobility_data

mobility_data$country_region <- reorder(mobility_data$country_region, -mobility_data$cu_cases)#factor(mobility_data$country_region, levels = case_countries)

doubled_counts = 2^seq(-2, 15, 1) * 100
double_times <- data.frame()
for (country in unique(mobility_data$country_region)) {
  
  df <-  mobility_data %>% filter(country_region == country)
  
  double_time <- 
    as.data.frame(
      as.Date(sapply(doubled_counts, 
             function(kk) #get moments of doubling
               optimize(function(t0) 
                 abs(approxfun(df$date, df$cu_cases)(t0) - kk),
                 interval = range(df$date))$minimum), 
      origin = "1970-01-01"))
  names(double_time) <- "doubling_time"

  double_times <-
    double_time %>%
    mutate(country_region = paste(country),
           cu_cases = doubled_counts,
           lag_cu_cases = lag(cu_cases),
           lag_doubling_time = lag(doubling_time),
           time = round(doubling_time - lag_doubling_time)) %>%
    distinct(doubling_time, .keep_all = TRUE) %>%
    filter(cu_cases <= max(df$cu_cases)) %>%
    rbind(double_times, .) 
  
}

double_times
max_cases<-
  mobility_data %>%
  group_by(country_region) %>%
  summarise(max_cu_cases = max(cu_cases)) %>%
  arrange(-max_cu_cases)

double_times$country_region <- factor(double_times$country_region, levels = max_cases$country_region)

mobility_data$country_region <- factor(mobility_data$country_region, levels = max_cases$country_region)
```



```{r}
lr_lab <-
  mobility_data %>% 
  filter(doubling_time < Inf) %>%
  group_by(country_region) %>%
  do(augment(loess(doubling_time ~ from_shutdown, .))) %>% 
  inner_join(. , mobility_data %>% dplyr::select(country_region, date, from_shutdown),
             by = c("country_region", "from_shutdown"))


cu<-
  ggplot(mobility_data %>%
           arrange(desc(date)),
         aes(x = date, 
             y = cu_cases,  
             group = country_region)) + 
  #geom_vline(data = double_times,
  #           aes(xintercept = doubling_time,
  #               group = country_region), linetype = 1, color = "grey80") +
  geom_vline(data = lr_lab %>%
               filter(.fitted <= 14,
                      .fitted > 1),
             aes(xintercept = date,
                 group = country_region, 
                 alpha = 1/.fitted), linetype = 1, color = "tomato", size = 4) +
  geom_segment(data = double_times,
               mapping = aes(x = lag_doubling_time,
                             xend = doubling_time,
                             y = cu_cases,
                             yend = cu_cases),
               color = "black",
               size = 0.5) +
  geom_segment(data = double_times,
               mapping = aes(x = lag_doubling_time,
                             xend = lag_doubling_time,
                             y = lag_cu_cases,
                             yend = cu_cases),
               color = "black",
               size = 0.5) +
  geom_line(size = 1) + 
  geom_line(data = mobility_data,
            aes(y = cu_deaths),
            color = "black",
            linetype = 3,
            size = 0.5) +
  geom_line(data = mobility_data,
            aes(y = total_tests),
            color = "black",
            size = 0.5,
            linetype = 2) +
  geom_point(data = mobility_data %>% 
               filter(from_shutdown == 0),
             aes(x = date,
                 y = cu_cases), 
             size = 3,
             shape = 21,
             fill = "yellow") +
  scale_alpha_continuous(range = c(0.001,0.2), trans = "log10") +
  guides(alpha = F) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-2, 15, 1) * 100,
                     trans = "log2",
                     limits = c(10, 10000000)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  ylab("Cumulative Cases\n(log2 scale)")+
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~country_region, scales = "free_x", space = "free_x")





lr <-
  ggplot(mobility_data %>%
           arrange(desc(date)),
         aes(x = date, 
             y = doubling_time, 
             group = country_region)) + 
  #geom_vline(data = double_times,
  #           aes(xintercept = doubling_time,
  #               group = country_region), linetype = 1, color = "grey80") +
  geom_vline(data = lr_lab %>%
               filter(.fitted <= 14,
                      .fitted > 1),
             aes(xintercept = date,
                 group = country_region, 
                 alpha = 1/.fitted), linetype = 1, color = "tomato", size = 4) +
  geom_point(size = 0.2) +
  #geom_smooth(method = "loess", se = FALSE, color = "black", size = 1) +
  geom_line(data = lr_lab,
            aes(x = date,
                y = .fitted)) +
  geom_point(data = lr_lab %>%
               filter(from_shutdown == 0),
             aes(x = date,
                 y = .fitted), 
             size = 3,
             shape = 21,
             fill = "yellow") +
  scale_alpha_continuous(range = c(0.001,0.2), trans = "log10") +
  guides(alpha = F) +
  scale_y_continuous(trans = reverselog_trans(2), 
                     breaks = c(2,4, 7,14,28, 56, 112),
                     labels = c("2 days", "4 days", "1 week", "2 weeks", "1 month", "2 months", "4 months")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  ylab("Doubling Time\n(log2 scale)")+
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~country_region, scales = "free_x", space = "free_x")

mob_lab <-
  mobility_data %>% 
  group_by(country_region) %>%
  do(augment(loess(residential_percent_change_from_baseline ~ from_shutdown, .))) %>% 
  inner_join(. , mobility_data %>% dplyr::select(country_region, date, from_shutdown),
             by = c("country_region", "from_shutdown")) %>%
  filter(from_shutdown == 0)

mob <-
  ggplot(mobility_data,
         aes(x = date, 
             y = residential_percent_change_from_baseline,
             group = country_region)) +
  #geom_vline(data = double_times,
  #           aes(xintercept = doubling_time,
  #               group = country_region), linetype = 1, color = "grey80") +
  geom_vline(data = lr_lab %>%
               filter(.fitted <= 14,
                      .fitted > 1),
             aes(xintercept = date,
                 group = country_region, 
                 alpha = 1/.fitted), linetype = 1, color = "tomato", size = 4) +
  geom_point(size = 0.2) +
  geom_smooth(method = "loess", se = FALSE, color = "black", size = 1) + 
  geom_point(data = mob_lab,
             aes(x = date,
                 y = .fitted), 
             size = 3,
             shape = 21,
             fill = "yellow") +
  geom_line(aes(x = date,
                y = StringencyIndex)) +
  scale_alpha_continuous(range = c(0.001,0.2), trans = "log10") +
  guides(alpha = F) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  labs(x = "Date", y = "Residential Mobility Trends\n(% change from baseline)") +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~country_region, scales = "free_x", space = "free_x")

plot_grid(cu,lr,mob,ncol=1, rel_heights = c(1,1,1.2), align = "v", axis = "b")

ggsave(paste0(covidFigPath, "doubling_time_red.jpg"), height = 15, width = 20)
```

##Morning Redo
```{r, warning=F}
case_limit <- 10

sp <-
  fread(paste0(covidPath, "Global_Mobility_Report.csv"), sep = ",", header = T) %>%
  filter(sub_region_1 == "",
         sub_region_2 == "")  %>% 
  mutate(date = as.Date(date)) %>%
  right_join( . ,
              case_study,
              by = c("country_region","date")) %>% 
  inner_join( . ,
              testing,
              by = c("country_region","date")) %>%
  group_by(country_region) %>%
  arrange(date) %>%
  filter(cu_cases > case_limit) %>%  
  mutate(cases_logratio = tsibble::difference(log(cu_cases)),
         doubling_time = log(2) / cases_logratio,
         days_elapsed = as.numeric(date - min(date)),
         max_case = max(cu_cases),
         max_days = max(days_elapsed),
         max_tests = max(total_tests_per_thousand, na.rm = T),
         ff = ifelse(country_region %in% case_countries,
                     "bold", "plain"),
         fs = ifelse(country_region %in% case_countries,
                     "1.5", "0.5"),
         fc = ifelse(country_region %in% case_countries,
                     "black", "grey60")) %>%
  arrange(country_region, date) %>%
  filter(doubling_time < Inf) %>%
  mutate(three_day_mean = 
           rollapply(doubling_time,  width = 3, 
                     FUN = mean, fill = NA)) %>%
  group_by(country_region,
           consec = {consec = rle(three_day_mean < 14); # find consec days
           rep(seq_along(consec$lengths),
               consec$lengths)}) %>%
  mutate(good_days = ifelse(three_day_mean <= 14, NA, seq_along(consec)),
         bad_days = ifelse(three_day_mean > 14, NA, seq_along(consec))) %>%
  ungroup() %>%
  group_by(country_region) %>%
  mutate(max_good_days = max(good_days, na.rm = T),
         max_bad_days = max(bad_days, na.rm = T),
         max_speed = max(three_day_mean),
         bad_day = ifelse(three_day_mean < 14, 1, 0)) %>%
  filter(max_tests > 1)
         #max_good_days > 14 | max_bad_days > 40

dc <-
  sp %>%
  group_by(country_region, ff) %>%
  dplyr::summarise(sum_bad = sum(bad_day, na.rm = T),
                   tests = max(total_tests_per_thousand, na.rm = T),
                   death = max(cu_deaths))
```


```{r}
hand_pick <-
  c("United States","Italy","Canada", "South Korea", "Singapore", "New Zealand", "Iceland","Australia","Austria", "Estonia","Slovenia","Greece", "Malaysia", "Switzerland", "Norway", "Denmark","Ireland","Portugal","Czech Republic", "France", "Germany", "Spain", "Netherlands", "Belgium", "Bahrain", "Finland", "Sweden", "United Kingdom", "Japan")

n_steps <- 100
alpha_gradient <- seq(from = 0.00001, to = 0, length.out = n_steps)
y_steps <- seq(from = -2, to = 14, length.out = n_steps + 1)

red_rect <- data.frame(ymin = y_steps[-(n_steps + 1)], 
                            ymax = y_steps[-1],
                            days_elapsed = 0,
                            doubling_time = 0,
                            alpha_gradient = alpha_gradient)


labs <-
  sp %>% 
  group_by(country_region, ff, fc, fs)%>%
  do(augment(loess(doubling_time ~ days_elapsed, .))) %>% 
  filter(country_region %in% hand_pick)
labs



spp<-
  ggplot(sp, 
         aes(x = days_elapsed, 
             y = doubling_time, 
             group = country_region)) + 
  scale_y_continuous(trans = reverselog_trans(2), 
                     breaks = c(2,4, 7,14,28, 56, 112, 224),
                     labels = c("2 days", "4 days", "1 week", "2 weeks", "1 month", "2 months", "4 months", "8 months"),
                     limits = c(max(sp$doubling_time),1)) +
  geom_rect(data=red_rect, 
            aes(xmin=0, xmax=max(sp$max_days),
                ymin=ymin, ymax=ymax, 
                alpha=alpha_gradient, group = 1), fill="tomato") +
  geom_hline(yintercept = 14, linetype = 2, color = "grey50", size = 0.1) +
  geom_line(data = labs %>%
              filter(!country_region %in% case_countries),
            aes(x = days_elapsed,
                y = .fitted,
                size = fs),
                color = "grey60") +
    geom_line(data = labs %>%
              filter(country_region %in% case_countries),
            aes(x = days_elapsed,
                y = .fitted,
                size = fs),
                color = "black") +
  geom_text_repel(data = labs %>%
                    filter(days_elapsed == max(days_elapsed)),
                  aes(x = days_elapsed, 
                      y = .fitted, 
                      label = country_region,
                      fontface = ff,
                      size = ff)) +
  scale_size_manual(values = c(0.7,1.5,6,5)) +
  scale_color_identity() +
  guides(size = F, alpha = F) +
  labs(x = paste0("Days since ",case_limit,"th reported case"),
       y = "Doubling time\n(log2 scale)")+
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))



dcc <-
ggplot(dc %>% filter(country_region %in% hand_pick),
       aes(x = sum_bad,
           y = death,
           label = country_region,
           size = tests)) +
  geom_point(alpha = 0.3) +
  geom_point(data = dc %>% 
               filter(tests == -Inf),
             size = 1,
             shape = 2) +
labs(x = "Days of Uncontrolled Spread",
     y = "Total COVID-19 deaths\n(log2 scale)") +
  scale_size_area(max_size = 14, 
                  breaks = c(10,20,40,80,100),
                  name = "Total tests\nper thousand") +
  scale_y_continuous(trans = "log2",
                     labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-4, 15, 1) * 100) +
  geom_text_repel(aes(fontface = ff),
                  size = 5) +
  theme_minimal() +
  theme(#legend.position = "bottom",
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15))






plot_grid(spp, dcc, nrow = 1, align = "h", axis = "l", rel_widths = c(1,1.3))

ggsave(paste0(covidFigPath, paste0("time_since",case_limit,".jpg")), height = 10, width = 22)
```


##CAN DELETE
```{r}


spp<-
  ggplot(sp, 
         aes(x = days_elapsed, 
             y = doubling_time, 
             group = country_region)) + 
  scale_y_continuous(trans = reverselog_trans(2), 
                     breaks = c(2,4, 7,14,28, 56, 112, 224),
                     labels = c("2 days", "4 days", "1 week", "2 weeks", "1 month", "2 months", "4 months", "8 months"),
                     limits = c(max(sp$doubling_time),1)) +
  geom_rect(data=red_rect, 
            aes(xmin=0, xmax=max(sp$max_days),
                ymin=ymin, ymax=ymax, 
                alpha=alpha_gradient, group = 1), fill="tomato") +
  #geom_rect(data=green_rect, 
  #          aes(xmin=0, xmax=80,
  #              ymin=ymin, ymax=ymax, 
  #              alpha=alpha_gradient, group = 1), fill="yellowgreen") +
  geom_hline(yintercept = 14, linetype = 2, color = "grey50", size = 0.1) +
  #geom_smooth(data = sp  %>%
  #              filter(!country_region %in% case_countries) %>%
  #         filter(country_region %in% hand_pick),
  #            method = "loess", se = FALSE, color = "grey50", size = 0.5) + 
  #geom_smooth(data = sp  %>%
  #              filter(country_region %in% case_countries),
  #            method = "loess", se = FALSE, color = "black", size = 1) + 
  geom_line(data = labs,
            aes(x = days_elapsed,
                y = .fitted,
                size = fs,
                color = fc)) +
  geom_text_repel(data = labs %>%
                    filter(days_elapsed == max(days_elapsed)),
                  aes(x = days_elapsed, 
                      y = .fitted, 
                      label = country_region,
                      fontface = ff,
                      size = ff)) +
  scale_size_manual(values = c(6,5)) +
  guides(size = F, alpha = F) +
  labs(x = paste0("Days since ",case_limit,"th reported case"),
       y = "Doubling time\n(log2 scale)")+
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))

```

##Provinces

```{r}
can_lockdown <- read.csv(paste0(covidPath,"../canada/can_lockdown.csv"), colClasses = c("character","character","Date"))

#github path
ishaberry_data_url <- "https://raw.githubusercontent.com/ishaberry/Covid19Canada/master/"
# cases.csv: Individual-level cases
#download.file(paste0(ishaberry_data_url,"cases.csv"), 
#              destfile = paste0(covidPath, "cases.csv"), quiet = T)
cases <- read.csv(paste0(covidPath, "cases.csv")) %>%
  mutate(date_report = as.Date(date_report, "%d-%m-%Y")) %>%
  group_by(date_report, province) %>%
  dplyr::summarise(prov_daily_total = n()) %>%
  group_by(province) %>%
  mutate(prov_cu_cases = cumsum(prov_daily_total))

cases

#Google mobility trends
#mobility_data_url <- "https://raw.githubusercontent.com/nacnudus/google-location-coronavirus/master/2020-04-05-country.tsv"
#download.file(mobility_data_url, destfile = paste0(covidPath, "2020-04-05-country.tsv"), quiet = T)

prov <-
  fread(paste0(covidPath, "2020-04-05-country.tsv"), sep = "\t", header = T) %>%
  filter(country_name == "Canada", 
         type == "region",
         category == "Residential") %>%
  dplyr::select(-c(url, page, row,col, group)) %>%
  mutate(date_report = as.Date(date),
         province = gsub("British Columbia","BC", region_name),
         province = gsub("Newfoundland and Labrador","NL", province)) %>%
  inner_join(. ,
             cases,
             by = c("province","date_report")) %>%
  inner_join( . ,
              can_lockdown,
              by = "region_name") %>%
  filter(prov_cu_cases > 10,
         prabb %in% c("QC","ON","AB","BC")) %>%
  arrange(date_report) %>%
  group_by(province) %>%
  mutate(cases_logratio = tsibble::difference(log(prov_cu_cases)),
         doubling_time = log(2) / cases_logratio,
         from_shutdown = as.numeric(difftime(date_report, lockdown_date, units = "days")),
         end_label = ifelse(date == max(date), prabb, NA),
         days_elapsed = as.numeric(date_report - min(date_report)))
  
prov$prabb <- reorder(prov$prabb, -prov$prov_cu_cases)
```

```{r}
p1 <-
  ggplot(prov,
         aes(x = from_shutdown, 
             y = prov_cu_cases, 
             color = prabb, 
             label = end_label, 
             group = prabb)) + 
  geom_vline(xintercept = 0) +
  geom_line(size = 1.5) + 
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since Social Distancing Policy") +
  ylab("CODID-19 Cases (log2 scale)")+
  theme_minimal()


p2 <-
 ggplot(prov,
         aes(x = from_shutdown, 
             y = doubling_time, 
             color = prabb, 
             label = end_label, 
             group = prabb))  + 
  geom_vline(xintercept = 0) +
  #geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Doubling Time")+
  theme_minimal() +
  ylim(c(0,14))

p2.5 <-
 ggplot(prov,
         aes(x = from_shutdown, 
             y = cases_logratio, 
             color = prabb, 
             label = end_label, 
             group = prabb)) + 
  geom_vline(xintercept = 0) +
  #geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  #geom_line() +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Log Ratio")+
  theme_minimal() +
  ylim(c(0,0.6))

p3 <-
 ggplot(prov,
         aes(x = from_shutdown, 
             y = trend, 
             color = prabb, 
             label = end_label, 
             group = prabb)) + 
  geom_vline(xintercept = 0) +
  #geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Residential mobility trends")+
  theme_minimal()
pp <-
plot_grid(p1,p2,p2.5,p3,ncol=1, align = "v", axis = "b")
pp
```

```{r}
cu<-
  ggplot(prov %>%
           arrange(desc(date_report)),
         aes(x = days_elapsed, 
             y = prov_cu_cases, 
             color = doubling_time, 
             label = end_label, 
             group = prabb)) + 
  geom_vline(data = prov %>% filter(from_shutdown == 0),
             aes(xintercept = days_elapsed),
             size = 0.5, linetype =2,
             color = "black") +
  geom_line(size = 1.5) + 
  geom_point(size = 1) + 
  guides(color = FALSE) + 
  scale_color_gradient(low = "tomato3", high = "yellow2") +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-2, 15, 1) * 100,
                     trans = "log2") + 
  ylab("Cumulative Number of Cases (log2 scale)")+
  theme_minimal() +
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA")) +
  facet_grid(.~prabb, scales = "free_x", space = "free_x")

lr <-
ggplot(prov %>%
           arrange(desc(date_report)),
         aes(x = days_elapsed, 
             y = doubling_time, 
             color = doubling_time, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(data = prov %>% filter(from_shutdown == 0),
             aes(xintercept = days_elapsed),
             size = 0.5, linetype =2,
             color = "black") +
  geom_point() +
  geom_smooth(method = "locfit",  size = 0.5, color = "black") + #se = FALSE,
  #geom_line(size = 0.5) +
  guides(color = FALSE) + 
  scale_color_gradient(low = "tomato3", high = "yellow2") +
  ylab("Doubling Time")+
  theme_minimal() +
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA")) +
  facet_grid(.~prabb, scales = "free_x", space = "free_x")

mobility <-
ggplot(prov %>%
           arrange(desc(date_report)),
         aes(x = days_elapsed, 
             y = trend,
             color = doubling_time)) +
  geom_vline(data = prov %>% filter(from_shutdown == 0),
             aes(xintercept = days_elapsed),
             size = 0.5, linetype =2,
             color = "black") +
  geom_point() +
  geom_smooth(method = "locfit",  size = 0.5, color = "black") +
  scale_color_gradient(low = "tomato3", high = "yellow2", breaks = c(2,7,14,21)) +
  labs(x = "Days Since 10th Confirmed Case", y = "Residential activity trends") +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.border = element_rect(color = "black", fill = "NA")) +
  facet_grid(.~prabb, scales = "free_x", space = "free_x")

plot_grid(cu,lr,mobility,ncol=1, rel_heights = c(1,1,1.2), align = "v", axis = "b")

ggsave(paste0(covidFigPath, "log_ratio_canada.jpg"), height = 8, width = 11)
```