---
title: "Covid Log Ratio"
author:
- name: Luke Anderson-Trocmé,
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---
# Load Libraries and set paths
```{r setup}
pacman::p_load(ggplot2) # plotting functions
pacman::p_load(cowplot) # combine plots
pacman::p_load(ggrepel) # repel label text
pacman::p_load(dplyr) # data wrangling
pacman::p_load(broom)
pacman::p_load(jsonlite)
pacman::p_load(data.table)
pacman::p_load(tidyverse)
pacman::p_load(tsibble) # for difference function
pacman::p_load(lubridate)
pacman::p_load(colorspace)
pacman::p_load(ggthemes)
pacman::p_load(locfit)


## rescale doubling time to reverse
#https://stackoverflow.com/questions/11053899/how-to-get-a-reversed-log10-scale-in-ggplot2
library("scales")
reverselog_trans <- function(base = exp(1)) {
  trans <- function(x) -log(x, base)
  inv <- function(x) base^(-x)
  trans_new(paste0("reverselog-", format(base)), trans, inv, 
            log_breaks(base = base), 
            domain = c(1e-100, Inf))
}


#Set Path
covidPath <- '~/Documents/covid19/data/world/'
covidFigPath <- '~/Documents/covid19/figures/'

today <- format(Sys.Date(), "%Y-%B-%d")
```
# Load Data
```{r, warning = F, message = F}
##################################################
# covdata
# https://github.com/kjhealy/covdata
#remotes::install_github("kjhealy/covdata")
##################################################

library("drat")
drat::addRepo("kjhealy")
install.packages("covdata")
library(tidyverse)
library(covdata)
library(ggrepel)
library(paletteer)
library(prismatic)

covnat
```

```{r}
us_states <- read.csv(paste0(covidPath, "states.csv"))
us_regions <- read.csv(paste0(covidPath, "US/state_regions.csv"))
us_lockdown <- read.csv(paste0(covidPath,"US/state_lockdown.csv")) %>%
  mutate(lockdown_date = as.Date(lockdown_date, format = "%B %d, %Y"))

## Countries to highlight
focus_states <- c("NY","NJ","MI","MA","PA")

## Which n states are leading the count of positive cases or deaths?
top <-10
top_n_states <- function(data, n = top, measure = c("positive", "death")) {
  meas <- match.arg(measure)
  data %>%
    group_by(region) %>%
    filter(measure == meas, date == max(date)) %>%
    drop_na() %>%
    ungroup() %>%
    top_n(n, wt = count) %>%
    pull(region)
}

state_cols <- c("gray70", 
                prismatic::clr_darken(paletteer_d("ggsci::category20_d3"), 0.2))

## Colors
cgroup_cols <- c(clr_darken(paletteer_d("ggsci::category20_d3"), 0.2)[1:top], "gray70")


cases <- 
  covus %>% filter(measure == "positive") %>% dplyr::select(state, date, count)

tests <- 
  covus %>% filter(measure %in% c('positive','negative')) %>% 
  group_by(state, date) %>%
  dplyr::summarise(test_count = sum(count))

deaths <- 
  covus %>% filter(measure == "death") %>% 
  rename(death_count = count) %>% dplyr::select(state, date, death_count) %>% arrange(state,date)


states <-
  fread(paste0(covidPath, "Global_Mobility_Report.csv"), sep = ",", header = T) %>%
  filter(country_region == "United States",
         sub_region_1 != "",
         sub_region_2 == "")  %>% 
  mutate(date = as.Date(date)) %>%
  inner_join( . ,
              us_regions,
              by = "sub_region_1") %>%
  inner_join( . ,
              us_lockdown,
              by = "sub_region_1") %>%
  inner_join(. ,
             cases,
             by = c("state","date")) %>%
  inner_join(. ,
             tests,
             by = c("state","date")) %>%
  inner_join(. ,
             deaths,
             by = c("state","date")) %>%
  filter(count > 10) %>%
  arrange(date) %>%
  group_by(state) %>%
  mutate(cases_logratio = tsibble::difference(log(count)),
         doubling_time = log(2) / cases_logratio,
         from_shutdown = as.numeric(difftime(date, lockdown_date, units = "days")),
         end_label = ifelse(date == max(date), state, NA),
         days_elapsed = as.numeric(date - min(date)),
         positive_rate = count / test_count * 1000,
         max_case = max(count, na.rm = T),
         total_tests = max(test_count, na.rm = T),
         total_deaths = max(death_count, na.rm = T))


states %>% filter(!is.na(end_label))

states <-
  states %>% 
  filter(doubling_time < Inf) %>%
  group_by(state) %>%
  do(augment(loess(doubling_time ~ days_elapsed, .))) %>% 
  inner_join(. , states,
             by = c("state", "days_elapsed", "doubling_time")) %>%
  mutate(max_days = max(days_elapsed, na.rm = T),
         end_label = ifelse(days_elapsed == max_days, 
                            as.character(state), NA))


states$state <- reorder(states$state, states$max_case)
states$division <- factor(states$division, levels = unique(states[order(states$region),]$division), ordered = TRUE)
states$state <- factor(states$state, levels = unique(states[order(states$division),]$state), ordered = TRUE)

death_count_usa <-
  states %>%
  group_by(state) %>%
  mutate(bad_day = ifelse(.fitted < 14, 1, 0)) %>%
  dplyr::summarise(tests = max(total_tests, na.rm = T),
                   death = max(total_deaths),
                   sum_bad = sum(bad_day))
```

#Fancy plotting tid bits 
```{r}
doubled_counts = 2^seq(-2, 15, 1) * 100
double_times_usa <- data.frame()
for (country in unique(states$state)) {
  
  df <-  states %>% filter(state == country)
  
  double_time <- 
    as.data.frame(
      as.Date(sapply(doubled_counts, 
                     function(kk) #get moments of doubling
                       optimize(function(t0) 
                         abs(approxfun(df$date, df$count)(t0) - kk),
                         interval = range(df$date))$minimum), 
              origin = "1970-01-01"))
  names(double_time) <- "doubling_time"
  
  double_times_usa <-
    double_time %>%
    mutate(state = paste(country),
           count = doubled_counts,
           lag_count = lag(count),
           lag_doubling_time = lag(doubling_time),
           time = round(doubling_time - lag_doubling_time)) %>%
    distinct(doubling_time, .keep_all = TRUE) %>%
    filter(count <= max(df$count)) %>%
    rbind(double_times_usa, .) 
}

double_times_usa$state <- 
  factor(double_times_usa$state, levels = levels(states$state))

## rescale doubling time to reverse
#https://stackoverflow.com/questions/11053899/how-to-get-a-reversed-log10-scale-in-ggplot2
library("scales")
reverselog_trans <- function(base = exp(1)) {
  trans <- function(x) -log(x, base)
  inv <- function(x) base^(-x)
  trans_new(paste0("reverselog-", format(base)), trans, inv, 
            log_breaks(base = base), 
            domain = c(1e-100, Inf))
}


n_steps <- 100
alpha_gradient <- seq(from = 0.00001, to = 0, length.out = n_steps)
y_steps <- seq(from = -2, to = 14, length.out = n_steps + 1)

red_rect <- data.frame(ymin = y_steps[-(n_steps + 1)], 
                       ymax = y_steps[-1],
                       days_elapsed = 0,
                       doubling_time = 0,
                       alpha_gradient = alpha_gradient)
```

#positive rate
```{r}
label_usa <- 
  states %>%
  filter(is.na(total_tests) == F,
         is.na(count) == F) %>%
  group_by(state) %>%
  top_n( ., 1, wt = days_elapsed) %>%
  mutate(end_label = state)


pr_usa <-
  ggplot(states %>%
           filter(is.na(positive_rate) == F),
         aes(x = days_elapsed, 
             y = positive_rate,  
             group = state,
             color = state,
             label = end_label)) + 
  #geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "locfit",size = 1, se = F) + 
  geom_text_repel(data = label_usa,
                  aes(x = days_elapsed, 
                      y = positive_rate,
                      group = state,
                      label = end_label),
                  color = "black") +
  labs(y = "Number of Cases per 1000 Tests",
       x = paste("Days Since",10,"Confirmed Cases")) +
  ggtitle("COVID-19 Positivity Rates by State") +
  scale_color_discrete_qualitative()+
  guides(color = F) +
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        plot.title = element_text(hjust = 0.5))


```


# Figure 1
```{r}
cu<-
  ggplot(states,
         aes(x = date, 
             y = count,  
             color = state,
             group = state,
             label = end_label)) + 
  #geom_vline(data = double_times_usa,
  #           aes(xintercept = doubling_time,
  #               group = state), linetype = 1, color = "grey80") +
  # geom_vline(data = states %>%
  #               filter(.fitted <= 14,
  #                      .fitted > 1),
  #             aes(xintercept = date,
  #                 group = state, 
  #                 alpha = 1/.fitted,
  #             label = end_label), linetype = 1, color = "tomato", size = 4) +
  #geom_segment(data = double_times_usa,
  #             mapping = aes(x = lag_doubling_time,
  #                           xend = doubling_time,
  #                           y = count,
  #                           yend = count),
  #             color = "black",
  #             size = 0.5) +
  #geom_segment(data = double_times_usa,
  #             mapping = aes(x = lag_doubling_time,
  #                          xend = lag_doubling_time,
  #                           y = lag_count,
  #                           yend = count),
  #             color = "black",
  #             size = 0.5) +
  geom_line(size = 1) + 
  geom_line(data = states,
            aes(y = death_count),
            linetype = 3,
            size = 0.5) +
  geom_line(data = states,
            aes(y = test_count),
            size = 0.5,
            linetype = 2) +
  geom_point(data = states %>% 
               filter(from_shutdown == 0),
             aes(x = date,
                 y = count), 
             size = 3,
             shape = 21,
             fill = "yellow") +
  geom_text_repel(data = label_usa,
                  aes(x = date, 
                      y = count,
                      group = state,
                      label = end_label)) +
  geom_text_repel(data = label_usa,
                  aes(x = date, 
                      y = death_count,
                      group = state,
                      label = end_label)) +
  geom_text_repel(data = label_usa,
                  aes(x = date, 
                      y = test_count,
                      group = state,
                      label = end_label)) +
  scale_alpha_continuous(range = c(0.001,0.2), trans = "log10") +
  scale_color_discrete_divergingx(palette = "Earth") +
  guides(alpha = F, label = F, shape = F, fill = F, color = F) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-2, 15, 1) * 100,
                     trans = "log2",
                     limits = c(10, 10000000)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  ylab("Cumulative Cases\n(log2 scale)")+
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~region, scales = "free_x", space = "free_x")


pr <-
  ggplot(states %>%
           filter(is.na(positive_rate) == F),
         aes(x = date, 
             y = positive_rate,
             color = state,  
             group = state,
             label = end_label)) + 
  #geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "locfit",size = 1, se = F) +
  geom_text_repel(data = label_usa,
                  aes(x = date, 
                      y = positive_rate,
                      group = state,
                      label = end_label),
                  color = "black") +
  scale_color_discrete_divergingx(palette = "Earth") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  labs(y = "Number of Cases per 1000 Tests",
       x = paste("Days Since",10,"Confirmed Cases")) +
  ggtitle("COVID-19 Positivity Rates by Divisaion") +
  guides(alpha = F, label = F, shape = F, fill = F, color = F) +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~region, scales = "free_x", space = "free_x")


lr <-
  ggplot(states,
         aes(x = date, 
             y = doubling_time,
             color = state, 
             group = state,
             label = end_label)) + 
  #geom_vline(data = double_times_usa,
  #           aes(xintercept = doubling_time,
  #               group = state), linetype = 1, color = "grey80") +
  # geom_vline(data = states %>%
  #               filter(.fitted <= 14,
  #                      .fitted > 1),
  #             aes(xintercept = date,
  #                 group = state, 
  #                 alpha = 1/.fitted,
  #             label = end_label), linetype = 1, color = "tomato", size = 4) +
  #geom_point(size = 0.2) +
  #geom_smooth(method = "loess", se = FALSE, color = "black", size = 1) +
  geom_line(data = states,
            aes(x = date,
                y = .fitted)) +
  geom_point(data = states %>%
               filter(from_shutdown == 0),
             aes(x = date,
                 y = .fitted), 
             size = 3,
             shape = 21,
             fill = "yellow") +
  geom_text_repel(data = label_usa,
                  aes(x = date, 
                      y = .fitted,
                      group = state,
                      label = end_label),
                  color = "black") +
  scale_alpha_continuous(range = c(0.001,0.2), trans = "log10") +
  scale_color_discrete_divergingx(palette = "Earth") +
  guides(alpha = F, label = F, shape = F, fill = F, color = F) +
  scale_y_continuous(trans = reverselog_trans(2), 
                     breaks = c(2,4, 7,14,28, 56, 112),
                     labels = c("2 days", "4 days", "1 week", "2 weeks", "1 month", "2 months", "4 months")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  ylab("Doubling Time\n(log2 scale)")+
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~region, scales = "free_x", space = "free_x")

mob_lab <-
  states %>% 
  group_by(state, division, region) %>%
  do(augment(loess(residential_percent_change_from_baseline ~ from_shutdown, .))) %>% 
  inner_join(. , states %>% dplyr::select(state, date, from_shutdown),
             by = c("state", "from_shutdown")) %>%
  filter(from_shutdown == 0)

mob <-
  ggplot(states,
         aes(x = date, 
             y = residential_percent_change_from_baseline,
             color = state,
             group = state,
             label = end_label)) +
  #geom_vline(data = double_times_usa,
  #           aes(xintercept = doubling_time,
  #               group = state), linetype = 1, color = "grey80") +
  # geom_vline(data = states %>%
  #               filter(.fitted <= 14,
  #                      .fitted > 1),
  #             aes(xintercept = date,
  #                 group = state, 
  #                 alpha = 1/.fitted,
  #             label = end_label), linetype = 1, color = "tomato", size = 4) +
  #geom_point(size = 0.2) +
  geom_smooth(method = "loess", se = FALSE, size = 1) + 
  geom_point(data = mob_lab,
             aes(x = date,
                 y = .fitted,
                 group = state,
                 label = NULL), 
             size = 3,
             shape = 21,
             fill = "yellow") +
  #geom_text_repel(data = label_usa,
  #                aes(x = date, 
  #                    y = residential_percent_change_from_baseline,
  #                    group = state,
  #                    label = end_label),
  #                color = "black") +
  scale_alpha_continuous(range = c(0.001,0.2), trans = "log10") +
  scale_color_discrete_divergingx(palette = "Earth") +
  guides(alpha = F, label = F, shape = F, fill = F, color = F) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b")+
  labs(x = "Date", y = "Residential Mobility Trends\n(% change from baseline)") +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 15,
                                  face = "bold")) +
  facet_grid(.~region, scales = "free_x", space = "free_x")

plot_grid(cu,pr,lr,mob,ncol=1, rel_heights = c(1,1,1,1.2), align = "v", axis = "b")

ggsave(paste0(covidFigPath, "doubling_time_usa_region.jpg"), height = 15, width = 35)
```



##fig2 usa
```{r}
spp<-
  ggplot() + 
  geom_rect(data = red_rect, 
            aes(xmin=0, xmax=max(states$max_days),
                ymin=ymin, ymax=ymax, 
                alpha=alpha_gradient, group = 1), size = 1, fill="tomato") +
  geom_hline(yintercept = 14, linetype = 2, color = "grey50", size = 0.1) +
  geom_line(data = states,
            aes(x = days_elapsed,
                y = .fitted,
                group = state),
            color = "grey60") +
  geom_line(data = states,
            aes(x = days_elapsed,
                y = .fitted,
                group = state),
            color = "black") +
  geom_text_repel(data = states, 
                  aes(x = days_elapsed,
                      y = .fitted,
                      group = state,
                      label = end_label),
                  segment.alpha = 0.1) +
  scale_y_continuous(trans = reverselog_trans(2), 
                     breaks = c(2,4, 7,14,28, 56, 112, 224),
                     labels = c("2 days", "4 days", "1 week", "2 weeks", "1 month", "2 months", "4 months", "8 months"),
                     limits = c(max(states$doubling_time),1)) +
  scale_size_manual(values = c(5,6,1.5,0.7)) +
  scale_color_identity() +
  guides(size = F, alpha = F) +
  labs(x = paste0("Days since ",10,"th reported case"),
       y = "Doubling time\n(log2 scale)")+
  theme_minimal() +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))


dcc <-
  ggplot(death_count_usa,
         aes(x = sum_bad,
             y = death,
             label = state,
             size = tests)) +
  geom_point(alpha = 0.3) +
  geom_point(data = death_count_usa %>% 
               filter(tests == -Inf),
             size = 1,
             shape = 2) +
  labs(x = "Days of Uncontrolled Spread",
       y = "Total COVID-19 deaths\n(log2 scale)") +
  scale_size_area(max_size = 14, 
                  breaks = c(10,20,40,80,100),
                  name = "Total tests\nper thousand") +
  scale_y_continuous(trans = "log2",
                     labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-4, 15, 1) * 100) +
  geom_text_repel(size = 5) +
  theme_minimal() +
  theme(#legend.position = "bottom",
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.border = element_rect(color = "black", fill = "NA"),
    axis.text = element_text(size = 15),
    axis.title = element_text(size = 15),
    legend.text = element_text(size = 15))


plot_grid(spp, dcc, nrow = 1, align = "h", axis = "l", rel_widths = c(1,1.3))

ggsave(paste0(covidFigPath, paste0("time_since",10,"usa.jpg")), height = 10, width = 22)

```





###################################################################
###################################################################
```{r}
cu<-
  ggplot(states %>%
           arrange(desc(date)),
         aes(x = days_elapsed, 
             y = count, 
             color = state, 
             label = end_label, 
             group = state)) + 
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") +
  #geom_vline(data = states %>% filter(from_shutdown == 0),
  #           aes(xintercept = days_elapsed),
  #           size = 0.5, linetype =2,
  #           color = "black") +
  geom_line(size = 1.5) + 
  guides(color = FALSE) + 
  #scale_color_gradient(low = "tomato3", high = "yellow2") +
  scale_color_discrete_divergingx(palette = "Earth") +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(-2, 15, 1) * 100,
                     trans = "log2") + 
  scale_x_continuous(breaks = seq(0, 28, 7)) +
  ylab("Cumulative Number of Cases (log2 scale)")+
  theme_minimal() +
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        #panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA")) +
  facet_grid(.~division, scales = "free_x", space = "free_x")

lr <-
  ggplot(states %>%
           arrange(desc(date)),
         aes(x = days_elapsed, 
             y = doubling_time, 
             color = state,  
             group = state)) + 
  geom_text(data = states %>% group_by(state, division) %>% 
              filter(doubling_time < Inf) %>%
              do(augment(loess(days_elapsed~doubling_time, .))) %>% 
              filter(days_elapsed == max(days_elapsed)),
            aes(days_elapsed, .fitted, label = state), nudge_x = 5) +
  #geom_vline(data = states %>% filter(from_shutdown == 0),
  #           aes(xintercept = days_elapsed),
  #           size = 0.5, linetype =2,
  #           color = "black") +
  #geom_point(size = 0.5) +
  geom_smooth(method = "locfit", se = FALSE,  size = 1, aes(color = state)) + #
  #geom_line(size = 0.5) +
  guides(color = FALSE) + 
  #scale_color_gradient(low = "tomato3", high = "yellow2") +
  scale_color_discrete_divergingx(palette = "Earth") +
  scale_x_continuous(breaks = seq(0, 28, 7)) +
  ylab("Doubling Time")+
  theme_minimal() +
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        panel.border = element_rect(color = "black", fill = "NA")) +
  facet_grid(.~division, scales = "free_x", space = "free_x") +
  ylim(c(0,24))

mobility <-
  ggplot(states %>%
           arrange(desc(date)),
         aes(x = days_elapsed, 
             y = residential_percent_change_from_baseline,
             color = state,
             group = state,
             label = end_label)) +
  geom_text(data = states %>% group_by(state, division) %>% 
              filter(doubling_time < Inf) %>%
              do(augment(loess(days_elapsed~residential_percent_change_from_baseline, .))) %>% 
              filter(days_elapsed == max(days_elapsed)),
            aes(days_elapsed, .fitted, label = state), nudge_x = 5) +
  #geom_vline(data = states %>% filter(from_shutdown == 0),
  #           aes(xintercept = days_elapsed),
  #           size = 0.5, linetype =2,
  #           color = "black") +
  #geom_point(size = 0.5) +
  geom_smooth(method = "locfit", se = FALSE, size = 1, aes(color = state)) +
  #scale_color_gradient(low = "tomato3", high = "yellow2", breaks = c(2,7,14,21)) +
  scale_color_discrete_divergingx(palette = "Earth") +
  scale_x_continuous(breaks = seq(0, 28, 7),
                     labels = paste("week", seq(1,5,1))) +
  guides(color = F) +
  labs(x = "Days Since 10th Confirmed Case", y = "Residential activity trends") +
  theme_minimal() +
  theme(legend.position = "bottom",
        panel.border = element_rect(color = "black", fill = "NA")) +
  facet_grid(.~division, scales = "free_x", space = "free_x")

plot_grid(cu,lr,mobility,ncol=1, rel_heights = c(1,1,1), align = "v", axis = "b")

ggsave(paste0(covidFigPath, "log_ratio_us_division.jpg"), height = 12, width = 18)
```


```{r}
## Countries to highlight
case_countries <- c("United States","Italy", "Sweden", "Denmark", "South Korea", "Singapore")
#focus_cn <- c("USA","KOR", "ITA", "DNK", "SGP", "SWE", "GBR", "ESP", "FRA", "CAN", "JPN", "NOR","AUT", "AUS")
#case_countries <- c("United States", "Italy", "United Kingdom", "Spain", "France","Canada", "Sweden", "Denmark", "South Korea", "Singapore", "Japan", "Norway","Austria","Australia")
lockdown <- read.csv(paste0(covidPath,"lockdown.csv"), colClasses = c("character","Date","Date"))
testing <- read.csv(paste0(covidPath,"owid-covid-data.csv")) %>%
  mutate(date = as.Date(date),
         country_region = location)

case_study <-
  covnat %>%
  filter(cu_cases > 10) %>%
  mutate(country_region = recode(cname, `Korea, Republic of` = "South Korea"))

mobility_data <- 
  fread(paste0(covidPath, "Global_Mobility_Report.csv"), sep = ",", header = T) %>%
  filter(sub_region_1 == "",
         sub_region_2 == "")  %>% 
  mutate(date = as.Date(date)) %>%
  right_join( . ,
              case_study,
              by = c("country_region","date")) %>% 
  inner_join( . ,
              testing,
              by = c("country_region","date")) %>%
  inner_join( . ,
              lockdown,
              by = "country_region") %>%
  filter(country_region %in% case_countries) %>%
  arrange(date) %>%
  group_by(country_region)%>% 
  mutate(cases_logratio = tsibble::difference(log(cu_cases)),
         doubling_time = log(2) / cases_logratio,
         from_shutdown = as.numeric(difftime(date, shutdown_date, units = "days")),
         end_label = ifelse(from_shutdown == max(from_shutdown), country_region, NA),
         days_elapsed = as.numeric(date - min(date))) #%>%
#filter(from_shutdown > -31)# %>%
#dplyr::select(country_region, date, from_shutdown, days_elapsed, cases_logratio,doubling_time, cu_cases, cu_deaths, trend,intersects, first_case, end_label)

mobility_data

mobility_data$country_region <- reorder(mobility_data$country_region, -mobility_data$cu_cases)#factor(mobility_data$country_region, levels = case_countries)

doubled_counts = 2^seq(-2, 15, 1) * 100
double_times <- data.frame()
for (country in unique(mobility_data$country_region)) {
  
  df <-  mobility_data %>% filter(country_region == country)
  
  double_time <- 
    as.data.frame(
      as.Date(sapply(doubled_counts, 
                     function(kk) #get moments of doubling
                       optimize(function(t0) 
                         abs(approxfun(df$date, df$cu_cases)(t0) - kk),
                         interval = range(df$date))$minimum), 
              origin = "1970-01-01"))
  names(double_time) <- "doubling_time"
  
  double_times <-
    double_time %>%
    mutate(country_region = paste(country),
           cu_cases = doubled_counts,
           lag_cu_cases = lag(cu_cases),
           lag_doubling_time = lag(doubling_time),
           time = round(doubling_time - lag_doubling_time)) %>%
    distinct(doubling_time, .keep_all = TRUE) %>%
    filter(cu_cases <= max(df$cu_cases)) %>%
    rbind(double_times, .) 
  
}

double_times
max_cases<-
  mobility_data %>%
  group_by(country_region) %>%
  summarise(max_cu_cases = max(cu_cases)) %>%
  arrange(-max_cu_cases)

double_times$country_region <- factor(double_times$country_region, levels = max_cases$country_region)

mobility_data$country_region <- factor(mobility_data$country_region, levels = max_cases$country_region)
```
