---
title: "Covid Log Ratio"
author:
- name: Luke Anderson-Trocmé,
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---
# Load Libraries and set paths
```{r setup}
pacman::p_load(ggplot2) # plotting functions
pacman::p_load(cowplot) # combine plots
pacman::p_load(ggrepel) # repel label text
pacman::p_load(dplyr) # data wrangling
pacman::p_load(jsonlite)
pacman::p_load(data.table)
pacman::p_load(tidyverse)
pacman::p_load(tsibble) # for difference function
pacman::p_load(lubridate)
pacman::p_load(colorspace)
pacman::p_load(ggthemes)
pacman::p_load(locfit)


#Set Path
covidPath <- '~/Documents/covid19/data/world/'
covidFigPath <- '~/Documents/covid19/figures/'

today <- format(Sys.Date(), "%Y-%B-%d")
```
# Load Data
```{r, warning = F, message = F}
##################################################
# covdata
# https://github.com/kjhealy/covdata
#remotes::install_github("kjhealy/covdata")
##################################################

library("drat")
drat::addRepo("kjhealy")
install.packages("covdata")
library(tidyverse)
library(covdata)

covnat
```

```{r}
## Libraries for the graphs
library(ggrepel)
library(paletteer)
library(prismatic)

## Convenince "Not in" operator
"%nin%" <- function(x, y) {
  return( !(x %in% y) )
}

## Countries to highlight
focus_cn <- c("CHN", "DEU", "GBR", "USA", "IRN", "JPN",
              "KOR", "ITA", "FRA", "ESP", "CHE", "TUR")

## Colors
cgroup_cols <- c(clr_darken(paletteer_d("ggsci::category20_d3"), 0.2)[1:length(focus_cn)], "gray70")

covnat %>%
  filter(cu_cases > 99) %>%
  mutate(days_elapsed = date - min(date),
        end_label = ifelse(date == max(date), cname, NA),
        end_label = recode(end_label, `United States` = "USA",
                            `Iran, Islamic Republic of` = "Iran",
                            `Korea, Republic of` = "South Korea",
                            `United Kingdom` = "UK"),
         cname = recode(cname, `United States` = "USA",
                        `Iran, Islamic Republic of` = "Iran",
                        `Korea, Republic of` = "South Korea",
                        `United Kingdom` = "UK"),
         end_label = case_when(iso3 %in% focus_cn ~ end_label,
                               TRUE ~ NA_character_), 
         cgroup = case_when(iso3 %in% focus_cn ~ iso3, 
                            TRUE ~ "ZZOTHER")) %>%
  ggplot(mapping = aes(x = days_elapsed, y = cu_cases, 
         color = cgroup, label = end_label, 
         group = cname)) + 
  geom_line(size = 0.5) + 
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA) + 
  guides(color = FALSE) + 
  scale_color_manual(values = cgroup_cols) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 2^seq(4, 19, 1),
                     trans = "log2") + 
  labs(x = "Days Since 100th Confirmed Case", 
       y = "Cumulative Number of Reported Cases (log2 scale)", 
       title = "Cumulative Reported Cases of COVID-19, Selected Countries", 
       subtitle = paste("ECDC data as of", format(max(covnat$date), "%A, %B %e, %Y")), 
       caption = "Kieran Healy @kjhealy / Data: https://www.ecdc.europa.eu/") +
  theme_minimal()
#> Don't know how to automatically pick scale for object of type difftime. Defaulting to continuous.
#> Warning: Removed 3018 rows containing missing values (geom_text_repel).

```

```{r}
us_states <- read.csv(paste0(covidPath, "states.csv"))
us_lockdown <- read.csv(paste0(covidPath,"US/state_lockdown.csv")) %>%
  mutate(lockdown_date = as.Date(lockdown_date, format = "%B %d, %Y"))

#Google mobility trends
#mobility_data_url <- "https://raw.githubusercontent.com/nacnudus/google-location-coronavirus/master/2020-04-05-country.tsv"
#download.file(mobility_data_url, destfile = paste0(covidPath, "2020-04-05-country.tsv"), quiet = T)

## Countries to highlight
focus_states <- c("NY","NJ","MI","MA","PA")

## Which n states are leading the count of positive cases or deaths?
top <-10
top_n_states <- function(data, n = top, measure = c("positive", "death")) {
  meas <- match.arg(measure)
  data %>%
  group_by(state) %>%
  filter(measure == meas, date == max(date)) %>%
  drop_na() %>%
  ungroup() %>%
  top_n(n, wt = count) %>%
  pull(state)
}

state_cols <- c("gray70", 
                prismatic::clr_darken(paletteer_d("ggsci::category20_d3"), 0.2))

## Colors
cgroup_cols <- c(clr_darken(paletteer_d("ggsci::category20_d3"), 0.2)[1:top], "gray70")

states <-
  states %>%
  ungroup() %>%
  mutate(state = as.factor(state))

states <-
  fread(paste0(covidPath, "2020-04-05-country.tsv"), sep = "\t", header = T) %>%
  filter(country_name == "United States", 
         type == "region",
         category == "Residential") %>%
  dplyr::select(-c(url, page, row,col, group)) %>%
  mutate(date = as.Date(date)) %>%
  inner_join( . ,
         us_states,
         by = "region_name") %>%
  inner_join(. ,
             covus %>% filter(measure == "positive"),
             by = c("state","date")) %>%
  inner_join( . ,
              us_lockdown,
              by = "region_name") %>%
  filter(count > 49) %>%
  arrange(date) %>%
  group_by(state) %>%
  mutate(cases_logratio = tsibble::difference(log(count)),
         doubling_time = log(2) / cases_logratio,
         from_shutdown = as.numeric(difftime(date, lockdown_date, units = "days")),
         core = case_when(state %nin% top_n_states(covus) ~ "",
                          TRUE ~ state),
         end_label = ifelse(date == max(date), core, NA),
         end_label = case_when(state %in% core ~ end_label,
                               TRUE ~ NA_character_),
         cgroup = case_when(state %in% core ~ state,
                            TRUE ~ "ZZOTHER"),
         days_elapsed = as.numeric(date - min(date))) %>%
  filter(from_shutdown > -15) %>%
  arrange(state %in% core) #%>%
  #dplyr::select(state, date, from_shutdown, days_elapsed, cases_logratio,doubling_time, count, deaths, trend, end_label)
  
states$state <- reorder(states$state, states$count)


state_tests <-
  covus %>%
  filter(measure %in% c('positive','negative')) %>%
  group_by(state, date) %>%
  dplyr::summarise(total_tests = sum(count, na.rm = T)) %>%
  inner_join( . ,
              states,
              by = c("state","date")) %>%
  arrange(date) %>%
  group_by(state) %>%
  mutate(tests_logratio = tsibble::difference(log(total_tests)),
         doubling_time = log(2) / tests_logratio)

```
 
 
```{r}
sc <-  
  ggplot(states %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")) %>%
           arrange(desc(date)),
         aes(x = from_shutdown, 
             y = count,
             color = cases_logratio,
             group = state)) +
  geom_vline(xintercept = 0) +
    geom_path(size = 0.5) +
    geom_path(data = state_tests %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")),
              aes(x = from_shutdown,
                  y = total_tests),
              color = "black",
              linetype = 2) +
    ggthemes::theme_hc() +
    scale_color_gradient(name="Log Ratio", low = "yellow2", high = "black") +
    scale_y_continuous(trans = "log2") +
    labs(x = "Days from Lockdown", y = "Cumulative Cases") +
  guides(color = F) +
  facet_grid(.~state, scales = "free_x", space = "free_x")

sl <-  
  ggplot(states %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")),
         aes(x = from_shutdown, 
             y = cases_logratio,
             group = state)) +
  geom_vline(xintercept = 0) +
  geom_point( color = "blue") +
  geom_smooth(method = "locfit", se = F, size = 0.5) +
  geom_smooth(data = state_tests %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")),
              aes(x = from_shutdown,
                  y = tests_logratio,
                  group = 1),
              method = "locfit",se = F, size = 0.5,
              color = "black") +
  ggthemes::theme_hc() +
  scale_color_gradient(name="Log Ratio", low = "yellow2", high = "black") +
  labs(x = "Days from Lockdown", y = "Log Ratio") +
  guides(color = F) +
  facet_grid(.~state, scales = "free_x", space = "free_x")

sd <-  
  ggplot(states %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")),
         aes(x = from_shutdown, 
             y = doubling_time,
             group = state)) +
  geom_vline(xintercept = 0) +
  geom_point() +
  geom_smooth(method = "locfit", se = F, size = 0.5) +
  geom_smooth(data = state_tests %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")),
              aes(x = from_shutdown,
                  y = doubling_time,
                  group = 1),
              method = "locfit",se = F, size = 0.5,
              color = "black") +
  ggthemes::theme_hc() +
  labs(x = "Days from Lockdown", y = "Doubling Time") +
  guides(color = F) +
  facet_grid(.~state, scales = "free_x", space = "free_x") +
  ylim(c(0,13))


sm<-
    ggplot(states %>%
           filter(state %in% c("NY","NJ","MI","MA","PA")),
         aes(x = from_shutdown, 
             y = trend,
             color = cases_logratio,
             group = state)) +
  geom_vline(xintercept = 0) +
  geom_point() +
  ggthemes::theme_hc() +
  scale_color_gradient(name="Log Ratio", low = "yellow2", high = "black") +
  labs(x = "Days from Lockdown", y = "Residential Mobility Trends") +
  guides(color = F) +
  facet_grid(.~state, scales = "free_x", space = "free_x")

plot_grid(sc,sl,sm,ncol = 1, align = "v", axis = "b", rel_heights = c(1,1,1.3))
```

```{r}

```

```{r}
p1 <-
  ggplot(states,
         aes(x = from_shutdown, 
             y = count, 
             color = cgroup, 
             label = end_label, 
             group = state)) + 
  geom_vline(xintercept = 0) +
  geom_line(size = 1.5) + 
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since Social Distancing Policy") +
  ylab("CODID-19 Cases (log2 scale)")+
  theme_minimal()


p2 <-
  ggplot(states,
         aes(x = from_shutdown, 
             y = doubling_time, 
             color = cgroup, 
             label = end_label, 
             group = state)) + 
  geom_vline(xintercept = 0) +
  #geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Doubling Time")+
  theme_minimal() +
  ylim(c(0,14))

p2.5 <-
  ggplot(states,
         aes(x = from_shutdown, 
             y = cases_logratio, 
             color = cgroup,
             label = end_label, 
             group = state)) + 
  geom_vline(xintercept = 0) +
  #geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  #geom_line() +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Log Ratio")+
  theme_minimal() +
  ylim(c(0,0.6))

p3 <-
  ggplot(states,
         aes(x = from_shutdown, 
             y = trend, 
             color = cgroup, 
             label = end_label, 
             group = state)) + 
  geom_vline(xintercept = 0) +
  #geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  scale_color_manual(values = cgroup_cols) +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Residential mobility trends")+
  theme_minimal()
pp <-
plot_grid(p1,p2,p2.5,p3,ncol=1, align = "v", axis = "b")

```

```{r}
## Countries to highlight
focus_cn <- c("USA","KOR", "ITA", "DNK", "SGP", "SWE", "GBR", "CAN")
case_countries <- c("United States", "Italy", "United Kingdom", "Canada", "Sweden", "Denmark", "South Korea", "Singapore")
lockdown <- read.csv(paste0(covidPath,"lockdown.csv"), colClasses = c("character","Date","Date"))

case_study <-
  covnat %>%
  filter(iso3 %in% focus_cn,
         cu_cases > 50) %>%
  mutate(country_name = recode(cname, `Korea, Republic of` = "South Korea")) %>%
  arrange(date)

mobility_data <- 
  fread(paste0(covidPath, "2020-04-05-country.tsv"), sep = "\t", header = T) %>%
  dplyr::select(-c(url, page, row,col, group)) %>%
  filter(type == "country",
         category == "Residential")  %>% 
  mutate(date = as.Date(date)) %>%
  filter(country_name %in% case_countries) %>%
  right_join( . ,
              case_study,
              by = c("country_name","date")) %>% 
  inner_join( . ,
              lockdown,
              by = "country_name") %>%
  arrange(date) %>%
  group_by(country_name) %>%
  mutate(cases_logratio = tsibble::difference(log(cu_cases)),
         doubling_time = log(2) / cases_logratio,
         from_shutdown = as.numeric(difftime(date, shutdown_date, units = "days")),
         end_label = ifelse(from_shutdown == max(from_shutdown), country_name, NA),
         days_elapsed = as.numeric(date - min(date))) %>%
  filter(from_shutdown > -31,
         from_shutdown < 41) %>%
  dplyr::select(country_name, date, from_shutdown, days_elapsed, cases_logratio,doubling_time, cu_cases, cu_deaths, trend, first_case, end_label)
  
mobility_data$country_name <- reorder(mobility_data$country_name, -mobility_data$cu_cases)#factor(mobility_data$country_name, levels = case_countries)

usa_tests <-
  covus %>%
  filter(measure %in% c('positive','negative')) %>%
  group_by(date) %>%
  dplyr::summarise(total_tests_USA = sum(count, na.rm = T)) %>%
  inner_join( . ,
              case_study %>% filter(iso3 == "USA"),
              by = "date")

```

```{r}
tt <- DT %>% 
  filter(cu_cases > 99, province == "Quebec") %>% 
  mutate(days_elapsed = Date - min(Date),
         end_label = ifelse(Date == max(Date), province, NA),
         cgroup = case_when(province %in% focus_cn ~ province,
                            TRUE ~ "ZZOTHER")
  )

f1 <- approxfun(tt$days_elapsed, log2(tt$cu_cases))
intersects_qc <- sapply(seq(4,19,1), function(kk) optimize(function(t0) abs(f1(t0) - kk), interval = range(tt$days_elapsed))$minimum)

tt_on <- DT %>% 
  filter(cu_cases > 99, province == "Ontario") %>% 
  mutate(days_elapsed = Date - min(Date),
         end_label = ifelse(Date == max(Date), province, NA),
         cgroup = case_when(province %in% focus_cn ~ province,
                            TRUE ~ "ZZOTHER")
  )

f1_on <- approxfun(tt_on$days_elapsed, log2(tt_on$cu_cases))
intersects_on <- sapply(seq(4,19,1), function(kk) optimize(function(t0) abs(f1_on(t0) - kk), interval = range(tt_on$days_elapsed))$minimum)

```


```{r}
cu<-
  ggplot(mobility_data %>%
           arrange(desc(date)),
         aes(x = from_shutdown, 
             y = cu_cases, 
             color = doubling_time, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_line(size = 1.5) + 
  geom_point(size = 1) + 
  guides(color = FALSE) + 
  scale_color_gradient(low = "tomato3", high = "yellow2", limits = c(0,27)) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  ylab("Cumulative Number of Reported Cases (log2 scale)")+
  theme_minimal() +
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(.~country_name, scales = "free_x", space = "free_x")

lr <-
  ggplot(mobility_data %>%
           arrange(desc(date)),
         aes(x = from_shutdown, 
             y = doubling_time, 
             color = doubling_time, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point() +
  #geom_smooth(method = "locfit",  size = 0.5) + #se = FALSE,
  #geom_line(size = 0.5) +
  guides(color = FALSE) + 
  scale_color_gradient(low = "tomato3", high = "yellow2", limits = c(0,27)) +
  ylab("Doubling Time")+
  theme_minimal() +
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  facet_grid(.~country_name, scales = "free_x", space = "free_x") +
  ylim(c(0,27))

mobility <-
  ggplot(mobility_data %>%
           arrange(desc(date)),
         aes(x = from_shutdown, 
             y = trend,
             color = doubling_time)) +
  geom_vline(xintercept = 0) +
  geom_point() +
  scale_color_gradient(low = "tomato3", high = "yellow2", limits = c(0,27)) +
  labs(x = "Days since lockdown", y = "Residential activity trends") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  facet_grid(.~country_name, scales = "free_x", space = "free_x")

plot_grid(cu,lr,mobility,ncol=1, rel_heights = c(1,1,1.2), align = "v", axis = "b")

ggsave(paste0(covidFigPath, "log_ratio_world.jpg"), height = 8, width = 11)
```


```{r}
p1 <-
  ggplot(mobility_data,
         aes(x = from_shutdown, 
             y = cu_cases, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_line(size = 0.5) + 
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Cumulative Number of Reported Cases (log2 scale)")+
  theme_minimal()


p2 <-
  ggplot(mobility_data,
         aes(x = from_shutdown, 
             y = doubling_time, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Doubling Time")+
  theme_minimal() +
  ylim(c(0,28))

p2.5 <-
  ggplot(mobility_data,
         aes(x = from_shutdown, 
             y = cases_logratio, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Log Ratio")+
  theme_minimal() +
  ylim(c(0,0.6))

p3 <-
  ggplot(mobility_data,
         aes(x = from_shutdown, 
             y = trend, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since Social Distancing Policy") +
  ylab("Residential mobility trends")+
  theme_minimal()
pp <-
plot_grid(p1,p2,p2.5,p3,ncol=1, align = "v", axis = "b")

d1 <-
  ggplot(mobility_data,
         aes(x = days_elapsed, 
             y = cu_cases, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_line(size = 0.5) + 
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since 50th Confirmed Case") +
  ylab("Cumulative Number of Reported Cases (log2 scale)")+
  theme_minimal()


d2 <-
  ggplot(mobility_data,
         aes(x = days_elapsed, 
             y = doubling_time, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  xlab("Days Since 50th Confirmed Case") +
  ylab("Doubling Time")+
  theme_minimal() +
  ylim(c(0,28))

d2.5 <-
  ggplot(mobility_data,
         aes(x = days_elapsed, 
             y = cases_logratio, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  xlab("Days Since 50th Confirmed Case") +
  ylab("Log Ratio")+
  theme_minimal() +
  ylim(c(0,0.6))

d3 <-
  ggplot(mobility_data,
         aes(x = days_elapsed, 
             y = trend, 
             color = country_name, 
             label = end_label, 
             group = country_name)) + 
  geom_vline(xintercept = 0) +
  geom_point(size = 0.5) + 
  geom_smooth(method = "locfit", se = F) +
  geom_text_repel(nudge_x = 0.75,
                  segment.color = NA,
                  fontface = "bold") + 
  colorspace::scale_color_discrete_qualitative() +
  guides(color = FALSE) + 
  scale_y_continuous(labels = scales::comma_format(accuracy = 1), 
                     breaks = 10^seq(1, 10, 1),
                     trans = "log2") + 
  xlab("Days Since 50th Confirmed Case") +
  ylab("Residential mobility trends")+
  theme_minimal()
dd <-
plot_grid(d1,d2,d2.5,d3,ncol=1, align = "v", axis = "b")

plot_grid(pp,dd, ncol = 2)
```

#by state
```{r}
covus

## Which n states are leading the count of positive cases or deaths?
top_n_states <- function(data, n = 5, measure = c("positive", "death")) {
  meas <- match.arg(measure)
  data %>%
  group_by(state) %>%
  filter(measure == meas, date == max(date)) %>%
  drop_na() %>%
  ungroup() %>%
  top_n(n, wt = count) %>%
  pull(state)
}

state_cols <- c("gray70", 
                prismatic::clr_darken(paletteer_d("ggsci::category20_d3"), 0.2))

covus %>%
  group_by(state) %>%
  mutate(core = case_when(state %nin% top_n_states(covus) ~ "",
                          TRUE ~ state),
         end_label = ifelse(date == max(date), core, NA)) %>%
  arrange(date) %>%
  filter(measure == "positive", date > "2020-03-09") %>%
  ggplot(aes(x = date, y = count, group = state, color = core, label = end_label)) + 
  geom_line(size = 0.5) + 
  geom_text_repel(segment.color = NA, nudge_x = 0.2, nudge_y = 0.1) + 
  scale_color_manual(values = state_cols) + 
  scale_x_date(date_breaks = "3 days", date_labels = "%b %e" ) + 
  scale_y_continuous(trans = "log2",
                     labels = scales::comma_format(accuracy = 1),
                     breaks = 2^c(seq(1, 17, 1))) +
  guides(color = FALSE) + 
  coord_equal() + 
  labs(title = "COVID-19 Cumulative Recorded Cases by US State",
       subtitle = paste("Data as of", format(max(covus$date), "%A, %B %e, %Y")),
       x = "Date", y = "Count of Cases (log 2 scale)", 
       caption = "Data: COVID Tracking Project, http://covidtracking.com | Graph: @kjhealy") + 
  theme_minimal()
```

```{r}
covus %>%
  arrange(date) %>%
  filter(measure == "positive",
         date > "2020-03-09") %>%
  #mutate(days_elapsed = date - min(date)) %>%
  dplyr::select(date, state, count) %>%
  arrange(date) %>%
  group_by(state) %>%
  mutate(cases_logratio = tsibble::difference(log(count))) %>%
  drop_na() %>%
  ggplot(. , aes(x = date, 
           y = cases_logratio,
           color = state, 
           group = state)) +
  geom_point() +
  geom_smooth(method = "locfit") +
  ggthemes::theme_hc() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  colorspace::scale_fill_discrete_qualitative() +
  colorspace::scale_color_discrete_qualitative() +
  guides(color = F) +
  xlab("Date") +
  ylab("Log Ratio") +
  facet_wrap(.~state, ncol = 10) +
  ylim(c(0,1))
```  
